Repository WildCodeSchool/202302-orleans-php-project2-abeille, pull requests merged in 2023-05, with the labels that each got.

#33 Fix spelling
  database.sql
  src/Controller/AssociationController.php
  src/Model/AbstractManager.php
  src/Model/AssociationManager.php
  src/View/Association/association.html.twig
  src/View/Home/association.html.twig
  src/routes.php
Labels: reviewed

#46 Fix fontsize et responsive
  public/assets/css/style.css
Labels: reviewed

#43 fix admin faq style
  public/assets/css/adminfaq.css
  src/View/Admin/Faq/adminAdd.html.twig
  src/View/Admin/Faq/adminIndex.html.twig
  src/View/Admin/Faq/adminUpdate.html.twig
  src/routes.php
Labels: reviewed

#42 S04US5
  public/assets/css/beekeeping.css
  public/assets/images/beekeeping.jpg
  public/assets/images/beekeeping2.jpg
  src/Controller/BeekeepingController.php
  src/View/Beekeeping/index.html.twig
  src/View/Item/_navbar.html.twig
  src/routes.php
Labels: reviewed

#48 style commun page admin
  public/assets/css/admin.css
  src/View/Admin/Event/adminIndex.html.twig
  src/View/Admin/Faq/adminIndex.html.twig
  src/View/Admin/Partner/index.html.twig
Labels: reviewed

#51 modification style
  public/assets/css/faq.css
  src/View/Resource/index.html.twig
Labels: reviewed

#44 S04 us09 admin page
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/View/Admin/Index/index.html.twig
  src/View/Admin/Partner/create.html.twig
  src/View/Admin/Partner/update.html.twig
  src/routes.php
Labels: reviewed, conflicts resolved

#50 Fix link navbar
  src/View/Home/footer.html.twig
  src/View/Item/_navbar.html.twig
  src/routes.php
Labels: reviewed, conflicts resolved

#53 image ajouter
  src/Controller/AdminPictureController.php
  src/Model/PictureManager.php
  src/View/Admin/Picture/adminAdd.html.twig
  src/View/Admin/Picture/adminIndex.html.twig
  src/routes.php
Labels: reviewed

#56 modifs page
  src/View/Admin/Index/index.html.twig
Labels: reviewed

#55 fix button style
  public/assets/css/style.css
  src/View/Home/footer.html.twig
Labels: reviewed

#54 S04US11
  database.sql
  src/Controller/ResourceController.php
  src/Model/LinkManager.php
  src/View/Resource/index.html.twig
Labels: reviewed

#49 S04 us10 contact
  public/assets/css/footer.css
  public/assets/css/style.css
  src/Controller/ContactController.php
  src/View/Admin/Partner/create.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Partner/update.html.twig
  src/View/Contact/contact.html.twig
  src/View/Home/footer.html.twig
  src/routes.php
Labels: reviewed, conflicts resolved

#59 modifs
  src/View/Admin/Index/index.html.twig
Labels: reviewed

#61 delete image
  src/Controller/AdminPictureController.php
  src/Model/PictureManager.php
  src/View/Admin/Picture/adminAdd.html.twig
  src/View/Admin/Picture/adminIndex.html.twig
  src/View/Admin/Picture/adminUpdate.html.twig
  src/routes.php
Labels: reviewed

#63 changer style header
  public/assets/css/beekeeping.css
  public/assets/images/beekeepingHeader.jpg
  src/View/Beekeeping/index.html.twig
Labels: changes requested

#58 S04 us6
  public/assets/css/abeilles.css
  public/assets/images/abeilles_abeilles.jpg
  public/assets/images/anatomie_abeille.jpg
  public/assets/images/vie_abeille.jpg
  src/Controller/BeeController.php
  src/View/Bees/index.html.twig
  src/routes.php
Labels: reviewed, conflicts resolved

#65 modif
  public/assets/css/footer.css
  public/assets/css/style.css
  src/View/Admin/Partner/create.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Partner/update.html.twig
Labels: reviewed

#67 fix bugs
  public/assets/css/abeilles.css
  src/View/Bees/index.html.twig
Labels: reviewed

#68 fix style
  public/assets/css/beekeeping.css
  public/assets/css/style.css
Labels: reviewed, conflicts resolved

#71 change style faq
  public/assets/css/faq.css
Labels: reviewed

#74 modif admin hover
  public/assets/css/admin.css
  public/assets/css/style.css
  src/View/Admin/Index/index.html.twig
Labels: reviewed

#70 css modif
  public/assets/css/style.css
  src/View/Association/association.html.twig
  src/View/Bees/index.html.twig
  src/View/Home/index.html.twig
Labels: reviewed

#75 change button admin
  public/assets/css/admin.css
  src/View/Admin/Event/adminAdd.html.twig
  src/View/Admin/Event/adminUpdate.html.twig
  src/View/Admin/Faq/adminAdd.html.twig
  src/View/Admin/Faq/adminUpdate.html.twig
  src/View/Admin/Partner/create.html.twig
  src/View/Admin/Partner/update.html.twig
Labels: reviewed

#72 S04US12
  public/assets/css/admin.css
  src/Controller/AdminLinkController.php
  src/Model/LinkManager.php
  src/View/Admin/Link/adminAdd.html.twig
  src/routes.php
Labels: reviewed, conflicts resolved

#77 fix border color
  public/assets/css/style.css
Labels: reviewed

#80 fixed h1 font-title
  public/assets/css/asso.css
Labels: reviewed

#82 created route and delete function
  src/Controller/AdminLinkController.php
  src/routes.php
Labels: reviewed

#84 Main to Dev
  public/assets/css/admin.css
  public/assets/css/asso.css
  public/assets/css/beekeeping.css
  public/assets/css/faq.css
  public/assets/css/style.css
  src/Controller/AdminLinkController.php
  src/Model/LinkManager.php
  src/View/Admin/Event/adminAdd.html.twig
  src/View/Admin/Event/adminUpdate.html.twig
  src/View/Admin/Faq/adminAdd.html.twig
  src/View/Admin/Faq/adminUpdate.html.twig
  src/View/Admin/Index/index.html.twig
  src/View/Admin/Link/adminAdd.html.twig
  src/View/Admin/Partner/create.html.twig
  src/View/Admin/Partner/update.html.twig
  src/View/Association/association.html.twig
  src/View/Bees/index.html.twig
  src/View/Home/index.html.twig
  src/routes.php
Labels: reviewed

#83 minor fixes layout and spelling
  src/View/Home/index.html.twig
Labels: reviewed

#87 Modif abeilles
  public/assets/css/admin.css
  src/View/Admin/Event/adminIndex.html.twig
  src/View/Admin/Faq/adminIndex.html.twig
  src/View/Admin/Link/adminAdd.html.twig
  src/View/Admin/Partner/create.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Partner/update.html.twig
  src/View/Admin/Picture/adminIndex.html.twig
Labels: reviewed

#73 modif contact
  public/assets/css/style.css
  src/View/Contact/contact.html.twig
Labels: reviewed

#92 modif background color html
  public/assets/css/style.css
Labels: reviewed

#91 fix_btn_admin
  public/assets/css/admin.css
  public/assets/css/footer.css
  src/View/Admin/Event/adminIndex.html.twig
  src/View/Admin/Faq/adminIndex.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Picture/adminIndex.html.twig
Labels: reviewed, conflicts resolved

#93 dev to main
  public/assets/css/admin.css
  public/assets/css/footer.css
  public/assets/css/style.css
  src/View/Admin/Event/adminIndex.html.twig
  src/View/Admin/Faq/adminIndex.html.twig
  src/View/Admin/Link/adminAdd.html.twig
  src/View/Admin/Partner/create.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Partner/update.html.twig
  src/View/Admin/Picture/adminIndex.html.twig
  src/View/Contact/contact.html.twig
  src/View/Home/index.html.twig
Labels: reviewed

#94 fix route event admin
  src/Controller/AdminEventController.php
  src/View/Admin/Index/index.html.twig
  src/routes.php
Labels: reviewed

#95 Fix mise en page
  public/assets/css/abeilles.css
  src/View/Bees/index.html.twig
Labels: reviewed

#79 new style link
  public/assets/css/faq.css
Labels: reviewed

#96 lien navbar login
  src/View/Item/_navbar.html.twig
Labels: reviewed

#98 style faq
  public/assets/css/faq.css
Labels: reviewed

#101 add svg view
  public/assets/css/footer.css
  src/View/Association/association.html.twig
  src/View/Contact/contact.html.twig
  src/View/Home/footer.html.twig
  src/View/Resource/index.html.twig
Labels: reviewed

#102 styled cards a bit more
  public/assets/css/home.css
Labels: reviewed

#89 Fix faq admin
  public/assets/css/admin.css
  src/Controller/AdminFaqController.php
  src/Controller/AdminLinkController.php
Labels: reviewed, conflicts resolved

#105 fix faq accordion
  public/assets/css/faq.css
Labels: reviewed

#103 modif return home button admin
  public/assets/css/admin.css
Labels: conflicts

#107 Fix pics
  public/assets/css/asso.css
  public/assets/css/home.css
  src/View/Association/association.html.twig
Labels: reviewed

#108 modif svg and button
  public/assets/css/admin.css
  src/View/Admin/Event/adminIndex.html.twig
  src/View/Admin/Faq/adminIndex.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Picture/adminIndex.html.twig
Labels: reviewed

#106 fix bouton admin
  database.sql
  public/assets/css/admin.css
  src/View/Admin/Event/adminIndex.html.twig
  src/View/Admin/Faq/adminIndex.html.twig
  src/View/Admin/Partner/index.html.twig
Labels: reviewed, conflicts resolved

#109 new style page
  public/assets/css/beekeeping.css
  src/View/Beekeeping/index.html.twig
Labels: reviewed, conflicts resolved

#110 fix font and cards
  public/assets/css/asso.css
  public/assets/css/home.css
  src/View/Home/index.html.twig
Labels: reviewed

#112 modifs padding
  public/assets/css/admin.css
Labels: reviewed

#111 border bottom table
  public/assets/css/admin.css
  public/assets/css/style.css
Labels: reviewed

#113 modif svg calendar
  src/View/Home/index.html.twig
Labels: reviewed

#115 Fix font
  public/assets/css/abeilles.css
  public/assets/css/beekeeping.css
  public/assets/css/style.css
Labels: reviewed

#117 style change
  public/assets/css/beekeeping.css
Labels: reviewed

#118 fix responsive
  public/assets/css/abeilles.css
Labels: reviewed

#116 responsive card date
  public/assets/css/asso.css
  public/assets/css/home.css
  src/View/Home/index.html.twig
Labels: reviewed

#119 dev to main
  database.sql
  public/assets/css/abeilles.css
  public/assets/css/admin.css
  public/assets/css/asso.css
  public/assets/css/beekeeping.css
  public/assets/css/faq.css
  public/assets/css/footer.css
  public/assets/css/home.css
  public/assets/css/partner.css
  public/assets/css/style.css
  src/Controller/AdminEventController.php
  src/Controller/AdminFaqController.php
  src/Controller/AdminLinkController.php
  src/View/Admin/Event/adminIndex.html.twig
  src/View/Admin/Faq/adminIndex.html.twig
  src/View/Admin/Index/index.html.twig
  src/View/Admin/Link/adminAdd.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Picture/adminIndex.html.twig
  src/View/Association/association.html.twig
  src/View/Beekeeping/index.html.twig
  src/View/Bees/index.html.twig
  src/View/Contact/contact.html.twig
  src/View/Home/footer.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_navbar.html.twig
  src/View/Resource/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: read please
